version: "3.9"
services:
    db-postgres:
        image: postgres:14.2-alpine
        env_file:
            - ./config/db-postgres/.env.dev
        volumes:
            - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
            - api-postgres:/var/lib/postgresql/data

    db-pgadmin:
        image: dpage/pgadmin4
        restart: always
        env_file:
            - ./config/db-pgadmin/.env.dev
        ports:
            - "5050:80"
networks:
    default:
        name: db_network

volumes:
    api-postgres:
